updated cicd config  to put env files in the right directory

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -80,6 +80,15 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Check if .env file exists
+        run: |
+          if [ -f ./backend/.env ]; then
+            echo ".env file exists"
+          else
+            echo ".env file not found"
+            exit 1
+          fi
+
       - name: Copy .env file to backend
         run: cp ./backend/.env ./backend/.env
 
